#%RAML 0.8
title: OICSecurityCredentialResource
version: v1.0-20150819
schemas:
 - Cred: !include schemas/oic.r.cred.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

/SecCredResURI:
  description: |
    This resource specifies credentials a device may use to establish secure communication.
  displayName: Credential Resource
  is: [ interface ]

  get:
    description: |
      Retrieves public credential data.
    responses:
      200:
        body:
          application/json:
            schema: Cred
            example: |
              {
                "creds": [
                  {
                    "credid": 55,
                    "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                    "roleid": {
                      "rl": {
                        "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                        "roles": [
                          "SOME_STRING", "SOME_STRING"
                        ]
                      }
                    },
                    "credtype": 32,
                    "publicdata": {
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE"
                    },
                    "privatedata": {
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE",
                      "handle": 4
                    },
                    "optionaldata": {
                      "revstat": false,
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE"
                    },
                    "period": "20160101T180000Z/20170102T070000Z",
                    "crms": [ "oic.sec.crm.pk10" ]
                  },
                  {
                    "credid": 55,
                    "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                    "subject": {
                      "idt": "0",
                      "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                    },
                    "roleid": {
                      "rl": {
                        "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                        "roles": [
                          "SOME_STRING", "SOME_STRING"
                        ]
                      }
                    },
                    "credtype": 1,
                    "publicdata": {
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE"
                    },
                    "privatedata": {
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE",
                      "handle": 4
                    },
                    "optionaldata": {
                      "revstat": false,
                      "encoding": "oic.sec.encoding.base64",
                      "data": "BASE-64-ENCODED-VALUE"
                    },
                    "period": "20160101T180000Z/20170102T070000Z",
                    "crms": [ "oic.sec.crm.pk10" ]
                  }
                ],
                "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                "rowner": {
                  "sl": [ "oic.sec.svc.doxs", "oic.sec.svc.bss" ]
                }
              }
      400:
        description: The request is invalid.

  post:
    description: |
      Sets or updates credential data
    body:
      application/json:
        schema: Cred
        example: |
          {
            "creds": [
              {
                "credid": 55,
                "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                "roleid": {
                  "rl": {
                    "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                    "roles": [
                      "SOME_STRING", "SOME_STRING"
                    ]
                  }
                },
                "credtype": 32,
                "publicdata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "privatedata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE",
                  "handle": 4
                },
                "optionaldata": {
                  "revstat": false,
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "period": "20160101T180000Z/20170102T070000Z",
                "crms": [ "oic.sec.crm.pk10" ]
              },

              {
                "credid": 55,
                "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                "subject": {
                  "idt": "0",
                  "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                },
                "roleid": {
                  "rl": {
                    "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                    "roles": [
                      "SOME_STRING", "SOME_STRING"
                    ]
                  }
                },
                "credtype": 1,
                "publicdata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "privatedata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE",
                  "handle": 4
                },
                "optionaldata": {
                  "revstat": false,
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "period": "20160101T180000Z/20170102T070000Z",
                "crms": [ "oic.sec.crm.pk10" ]
              }
            ],
            "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
            "rowner": {
              "sl": [ "oic.sec.svc.doxs", "oic.sec.svc.bss" ]
              }
            }
    responses:
      201:
        description: The credential entry is created.
      204:
        description: The credential entry is updated.
      400:
        description: The request is invalid.

  put:
    description: Updates credential data
    body:
      application/json:
        schema: Cred
        example: |
          {
            "creds": [
              {
                "credid": 55,
                "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                "roleid": {
                  "rl": {
                    "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                    "roles": [
                      "SOME_STRING", "SOME_STRING"
                    ]
                  }
                },
                "credtype": 32,
                "publicdata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "privatedata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE",
                  "handle": 4
                },
                "optionaldata": {
                  "revstat": false,
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "period": "20160101T180000Z/20170102T070000Z",
                "crms": [ "oic.sec.crm.pk10" ]
              },

              {
                "credid": 55,
                "subjectuuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                "subject": {
                  "idt": "0",
                  "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                },
                "roleid": {
                  "rl": {
                    "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                    "roles": [
                      "SOME_STRING", "SOME_STRING"
                    ]
                  }
                },
                "credtype": 1,
                "publicdata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "privatedata": {
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE",
                  "handle": 4
                },
                "optionaldata": {
                  "revstat": false,
                  "encoding": "oic.sec.encoding.base64",
                  "data": "BASE-64-ENCODED-VALUE"
                },
                "period": "20160101T180000Z/20170102T070000Z",
                "crms": [ "oic.sec.crm.pk10" ]
              }
            ],
            "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
            "rowner": {
              "sl": [ "oic.sec.svc.doxs", "oic.sec.svc.bss" ]
            }
          }
    responses:
         201:
            description: The credential entry is created.
         400:
            description: The request is invalid.

  delete:
      description: |
        Deletes the credential data.
        When DELETE is used without query parameters, the entire collection is deleted.
        When DELETE uses a query value naming the subject, only the matched entry is deleted.
      queryParameters:
        subject:
          type: string
          description: |
            Delete the credential identified by the string containing subject id.
            required: false
            example: |
              DELETE /mycred?subject="de305d54-75b4-431b-adb2-eb6b9e546014"
      responses:
        204:
          description: The credential instance or the the entire credential resource has been successfully deleted.
        400:
          description: The request is invalid.
