#%RAML 0.8
title: OIC Security Acl Resource
version: v1.0-20150819
schemas:
- Acl: !include oic.sec.acl.json

traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.baseline"]

/oic/sec/acl:
  description: |
    This resource specifies the local access control list.

  displayName: Access Control List data
  is: [ interface ]

  get:
    description: |
      Retrieves the acl data.
    responses:
      200:
        body:
          application/json:
            schema: acl
            example: |
              {
                "rt": "oic.sec.acl",
                "acl":[
                    {
                      "subject":  "de305d54-75b4-431b-adb2-eb6b9e546014",
                      "resources":[ "/oic/light", "oic/light"],                                
                      "permission": 15,
                      "period":     ["20150101T180000Z/20150102T070000Z"],
                      "recurrence": ["RRULE:FREQ=WEEKLY;UNTIL=20150131TO70000Z"],
	                  "rowner": ["oic.sec.svc.ams"]                  
                    },
                    {
                      "subject":  "de305d54-75b4-431b-adb2-eb6b9e546014",
                      "resources":[ "/oic/door","oic/light"],
                      "permission": 15,
	                  "rowner": ["oic.sec.svc.ams"]                  
                    }
                  ],
              }
      400:
        description: The request is invalid.

  post:
    description: |
      Updates the acl resource with the provided values.
    body:
      application/json:
        schema: acl
        example: |
          {
                "rt": "oic.sec.acl",
                "acl":[
                    {
                      "subject":  "de305d54-75b4-431b-adb2-eb6b9e546014",
                      "resources":[ "/oic/light", "oic/light"],                                
                      "permission": 15,
                      "period":     ["20150101T180000Z/20150102T070000Z"],
                      "recurrence": ["RRULE:FREQ=WEEKLY;UNTIL=20150131TO70000Z"],
	                  "rowner": ["oic.sec.svc.ams"]                  
                    },
                    {
                      "subject":  "de305d54-75b4-431b-adb2-eb6b9e546014",
                      "resources":[ "/oic/door","oic/light"],
                      "permission": 15,
	                  "rowner": ["oic.sec.svc.ams"]                  
                    }
                  ],
              }
    responses:
      201:
        description: The ACL entry is created.
      204:
        description: The ACL entry is updated.
      400:
        description: The request is invalid.

  put:
    description: |
      Creates the new acl data
    body:
      application/json:
        schema: acl
        example: |
          {
                "rt": "oic.sec.acl",
                "acl":[
                    {
                      "subject":  "de305d54-75b4-431b-adb2-eb6b9e546014",
                      "resources":[ "/oic/light", "oic/light"],                                
                      "permission": 15,
                      "period":     ["20150101T180000Z/20150102T070000Z"],
                      "recurrence": ["RRULE:FREQ=WEEKLY;UNTIL=20150131TO70000Z"],
	                  "rowner": ["oic.sec.svc.ams"]                  
                    },
                    {
                      "subject":  "de305d54-75b4-431b-adb2-eb6b9e546014",
                      "resources":[ "/oic/door","oic/light"],
                      "permission": 15,
	                  "rowner": ["oic.sec.svc.ams"]                  
                    }
                  ],
              }
    responses:
      201:
        description: The ACL entry is created.
      400:
        description: The request is invalid.

  delete:
    description: |
      Deletes the acl data.
      When DELETE is used without query parameters, the entire collection is deleted.
      When DELETE uses the search parameter with "subject", only the matched entry is deleted.
    queryParameters:
        subject:
            type: string
            description: |
              Delete the ACL identified by the string containing subject UUID.
              e.g. DELETE /oic/sec/acl ?subject="de305d54-75b4-431b-adb2-eb6b9e546014"
            required: false

    responses:
      200:
        description: The ACL instance or the the entire ACL resource has been successfully deleted.
      400:
        description: The request is invalid.
