#%RAML 0.8
title: OIC Security Amacl Resource
version: v1.0-20150819
schemas:
  - Amacl: !include oic.sec.amacl.json

traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.baseline"]

/oic/sec/amacl:
  description: |
    This resource specifies the host resources with access permission that is managed by an AMS.

  displayName: Managed Access Control data
  is: [ interface ]

  get:
    description: |
      Retrieves the amacl data.
    responses:
      200:
        body:
          application/json:
            schema: amacl
            example: |
              {
                "rt": "oic.sec.amacl",
                "resources":
                  ["/oic/light"],
                "ams":["oic.sec.svc.ams"],
                "rowner":["oic.sec.svc.ams"]
              }

  post:
    description: |
      Sets the new amacl data
    body:
      application/json:
        schema: amacl
        example: |
          {
                "rt": "oic.sec.amacl",
                "resources":
                  ["/oic/light"],
                "ams":["oic.sec.svc.ams"],
                "rowner":["oic.sec.svc.ams"]
          }
    responses:
      201:
        description: The AMACL entry is created.
      204:
        description: The AMACL entry is updated.
      400:
        description: The request is invalid.

  put:
    description: |
      Creates the new acl data
    body:
      application/json:
        schema: amacl
        example: |
           {
                "rt": "oic.sec.amacl",
                "resources":
                  ["/oic/light"],
                "ams":["oic.sec.svc.ams"],
                "rowner":["oic.sec.svc.ams"]
          }
    responses:
      201:
        description: The AMACL entry is created.
      400:
        description: The request is invalid.

  delete:
    description: |
      Deletes the amacl data.
      When DELETE is used without query parameters, the entire collection is deleted.
      When DELETE uses the search parameter with "subject", only the matched entry is deleted.
    queryParameters:
        subject:
            type: string
            description: |
              Delete the ACE identified by the string matching the subject value.
            required: false
            example: |
              DELETE /oic/sec/amacl?subject="de305d54-75b4-431b-adb2-eb6b9e546014"
    responses:
      200:
        description: The ACE instance or the the entire AMACL resource has been successfully deleted.
      400:
        description: The request is invalid.
