#%RAML 0.8
title: OICSecurityServicesResource
version: v1.0-20150819
schemas:
  - Svc: !include ../json-schemas/oic.r.svc.json

traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.baseline"]

/SecSvcResURI:
  description: |
    This resource specifies the services this device recognizes.

  displayName: Services Resource data
  is: [ interface ]

  get:
    description: |
      Retrieves the services resource data.
    responses:
      200:
        body:
          application/json:
            schema: Svc
            example: |
              {
                  "hosts": [
                    {
                      "hostid": {
                      "idt": "0",
                      "id": "de305d54-75b4-431b-adb2-eb6b9e546014"
                      },
                      "svcs": {
                        "sl": [ "oic.sec.svc.doxs" ]
                      },
                      "sct": 32,
                      "scid": 1,
                      "ccid": 1,
                      "crms": [ "oic.sec.crm.psk" ]
                    },
                    {
                      "hostid": {
                        "idt": "0",
                        "id": "de305d54-75b4-431b-adb2-eb6b9e546015"
                      },
                      "svcs": {
                        "sl": [ "oic.sec.svc.bss" ]
                      },
                      "sct": 16,
                      "scid": 2,
                      "ccid": 2,
                      "crms": [ "oic.sec.crm.pro", "oic.sec.crm.psk" ]
                    },
                    {
                      "hostid": {
                        "idt": "0",
                        "id": "de305d54-75b4-431b-adb2-eb6b9e546016"
                      },
                      "svcs": {
                        "sl": [ "oic.sec.svc.cms", "oic.sec.svc.ams" ]
                      },
                      "sct": 1,
                      "scid": 3,
                      "ccid": 4,
                      "crms": [ "oic.sec.crm.pro", "oic.sec.crm.psk", "oic.sec.crm.pk10" ]
                    }
                  ],
                  "rowner": {
                    "sl": ["oic.sec.svc.doxs", "oic.sec.svc.bss"]
                  }
              }
      400:
        description: The request is invalid.

  post:
    description: |
      Updates a services resource entry
    body:
      application/json:
        schema: Svc
        example: |
          {
            "hosts": [
              {
                "hostid": {
                "idt": "0",
                "id": "de305d54-75b4-431b-adb2-eb6b9e546014"
                },
                "svcs": {
                  "sl": [ "oic.sec.svc.doxs" ]
                },
                "sct": 32,
                "scid": 1,
                "ccid": 1,
                "crms": [ "oic.sec.crm.psk" ]
              },
              {
                "hostid": {
                  "idt": "0",
                  "id": "de305d54-75b4-431b-adb2-eb6b9e546015"
                },
                "svcs": {
                  "sl": [ "oic.sec.svc.bss" ]
                },
                "sct": 16,
                "scid": 2,
                "ccid": 2,
                "crms": [ "oic.sec.crm.pro", "oic.sec.crm.psk" ]
              },
              {
                "hostid": {
                  "idt": "0",
                  "id": "de305d54-75b4-431b-adb2-eb6b9e546016"
                },
                "svcs": {
                  "sl": [ "oic.sec.svc.cms", "oic.sec.svc.ams" ]
                },
                "sct": 1,
                "scid": 3,
                "ccid": 4,
                "crms": [ "oic.sec.crm.pro", "oic.sec.crm.psk", "oic.sec.crm.pk10" ]
              }
            ],
            "rowner": {
              "sl": ["oic.sec.svc.doxs", "oic.sec.svc.bss"]
            }
          }
    responses:
      201:
        description: The PSTAT entry is created.
      204:
        description: The PSTAT entry is updated.
      400:
        description: The request is invalid.

  put:
    description: |
      Creates a new services resource entry
    body:
      application/json:
        schema: Svc
        example: |
          {
            "hosts": [
              {
                "hostid": {
                "idt": "0",
                "id": "de305d54-75b4-431b-adb2-eb6b9e546014"
                },
                "svcs": {
                  "sl": [ "oic.sec.svc.doxs" ]
                },
                "sct": 32,
                "scid": 1,
                "ccid": 1,
                "crms": [ "oic.sec.crm.psk" ]
              },
              {
                "hostid": {
                  "idt": "0",
                  "id": "de305d54-75b4-431b-adb2-eb6b9e546015"
                },
                "svcs": {
                  "sl": [ "oic.sec.svc.bss" ]
                },
                "sct": 16,
                "scid": 2,
                "ccid": 2,
                "crms": [ "oic.sec.crm.pro", "oic.sec.crm.psk" ]
              },
              {
                "hostid": {
                  "idt": "0",
                  "id": "de305d54-75b4-431b-adb2-eb6b9e546016"
                },
                "svcs": {
                  "sl": [ "oic.sec.svc.cms", "oic.sec.svc.ams" ]
                },
                "sct": 1,
                "scid": 3,
                "ccid": 4,
                "crms": [ "oic.sec.crm.pro", "oic.sec.crm.psk", "oic.sec.crm.pk10" ]
              }
            ],
            "rowner": {
              "sl": ["oic.sec.svc.doxs", "oic.sec.svc.bss"]
            }
          }
    responses:
      201:
        description: The PSTAT entry is created.
      400:
        description: The request is invalid.

  delete:
    description: |
      Deletes the SVC data.
      When DELETE is used without query parameters, the entire collection is deleted.
      When DELETE is used with the query parameter where "svcid" is specified, only the matched entry is deleted.
    queryParameters:
        subject:
            type: string
            description: |
              Delete the PSTAT identified by the string containing the UUID.
            required: false
            example: |
              DELETE /mysvc?svcid="de305d54-75b4-431b-adb2-eb6b9e546014"
    responses:
      200:
        description: The SVC instance or the the entire resource has been successfully deleted.
      400:
        description: The request is invalid.
