#%RAML 0.8
title: OICSecurityDoxmResource
version: v1.0-20150819
schemas:
  - Doxm: !include ../json-schemas/oic.r.doxm.json

traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.baseline"]

/SecDoxmResURI:
  description: |
    This resource specifies properties needed to establish a device owner.

  displayName: Device owner transfer method resource data
  is: [ interface ]

  get:
    description: |
      Retrieves the DOXM resource data.
    responses:
      200:
        body:
          application/json:
            schema: Doxm
            example: |
              {
                "oxms": [ 0, 2, 3 ],
                "oxmsel": 0,
                "sct": 16,
                "owned": true,
                "deviceuuid": "de305d54-75b4-431b-adb2-eb6b9e546014",
                "deviceid": {
                  "idt": "0",
                  "id": "de305d54-75b4-431b-adb2-eb6b9e546014"
                },
                "devowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                "devowner": {
                    "hostid": {
                      "idt": "0",
                      "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                    }
                },
                "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                "rowner": {
                  "sl": ["oic.sec.svc.bss", "oic.sec.svc.doxs"]
                }
              }

      400:
        description: The request is invalid.

  post:
    description: |
      Updates the DOXM resource data
    body:
      application/json:
        schema: Doxm
        example: |
          {
            "oxms": [ 0, 2, 3 ],
            "oxmsel": 0,
            "sct": 16,
            "owned": true,
            "deviceuuid": "de305d54-75b4-431b-adb2-eb6b9e546014",
            "deviceid": {
              "idt": "0",
              "id": "de305d54-75b4-431b-adb2-eb6b9e546014"
            },
            "devowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
            "devowner": {
                "hostid": {
                  "idt": "0",
                  "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                }
            },
            "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
            "rowner": {
              "sl": ["oic.sec.svc.bss", "oic.sec.svc.doxs"]
            }
          }
    responses:
      201:
        description: The DOXM entry is created.
      204:
        description: The DOXM entry is updated.
      400:
        description: The request is invalid.

  put:
    description: |
      Creates the DOXM resource data
    body:
      application/json:
        schema: Doxm
        example: |
          {
            "oxms": [ 0, 2, 3 ],
            "oxmsel": 0,
            "sct": 16,
            "owned": true,
            "deviceuuid": "de305d54-75b4-431b-adb2-eb6b9e546014",
            "deviceid": {
              "idt": "0",
              "id": "de305d54-75b4-431b-adb2-eb6b9e546014"
            },
            "devowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
            "devowner": {
                "hostid": {
                  "idt": "0",
                  "id": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9"
                }
            },
            "rowneruuid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
            "rowner": {
              "sl": ["oic.sec.svc.bss", "oic.sec.svc.doxs"]
            }
          }
    responses:
      201:
        description: The DOXM entry is created.
      400:
        description: The request is invalid.

  delete:
      description: |
        Deletes the DOXM data.
        When DELETE is used without query parameters, the entire DOXM resource is deleted.
        When DELETE uses a query value naming the deviceid, only the matched entry is deleted.
      queryParameters:
          subject:
              type: string
              description: |
                Delete the DOXM entry identified by the string containing device ID.
              required: false
              example: |
                DELETE /mydoxm?deviceid="de305d54-75b4-431b-adb2-eb6b9e546014"
      responses:
        204:
          description: The CRL instance or the the entire CRL resource has been successfully deleted.
        400:
          description: The request is invalid.
