#%RAML 0.8
title: OICSecuritySignedAclResource
version: v1.0-20150819
schemas:
  - Sacl: !include ../json-schema/oic.r.sacl.json

traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.baseline"]

/SecSaclResURI:
  description: |
    This resource specifies a signed ACL object.

  displayName: Signed Access Control List data
  is: [ interface ]

  get:
    description: |
      Retrieves the sacl resource data.
    responses:
      200:
        body:
          application/json:
            schema: Sacl
            example: |
              {
                "aclist": {
                  "aces": [
                    {
                      "subjectid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                      "resources": [
                        {
                          "href": "coaps://IP-ADDR/temp",
                          "rel": "some-rel",
                          "rt": "oic.r.temperature",
                          "if": "oic.if.a"
                        },
                        {
                          "href": "coaps://IP-ADDR/temp",
                          "rel": "some-rel",
                          "rt": "oic.r.temperature",
                          "if": "oic.if.s"
                        }
                      ],
                      "permission": 31,
                      "validity": [
                        [ "20160101T180000Z/20170102T070000Z", [ "DSTART:XXXXX", "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ] ],
                        [ "20160101T180000Z/PT5H30M", [ "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ] ]
                      ]
                    }
                  ],
                  "aces2": [
                    {
                      "subject": {
                        "rl": {
                          "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                          "roles": [
                            "SOME_STRING", "SOME_STRING"
                          ]
                        }
                      },
                      "resources": [
                        {
                          "href": "coaps://IP-ADDR/light",
                          "rel": "some-rel",
                          "rt": "oic.r.light",
                          "if": "oic.if.a"
                        },
                        {
                          "href": "coaps://IP-ADDR/door",
                          "rel": "some-rel",
                          "rt": "oic.r.door",
                          "if": "oic.if.a"
                        }
                      ],
                      "permission": 15
                    }
                  ]

                },
                "signature": {
                  "sigtype": "oic.sec.sigtype.pk7",
                  "sigvalue": "ENCODED-SIGNATURE-VALUE"
                },
                "amsid": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                "ams": {
                  "sl": [ "oic.sec.svc.doxs", "oic.sec.svc.bss" ]
                }
              }

  post:
    description: |
      Sets the sacl resource data
    body:
      application/json:
        schema: Sacl
        example: |
          {
            "aclist": {
              "aces": [
                {
                  "subjectid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                  "resources": [
                    {
                      "href": "coaps://IP-ADDR/temp",
                      "rel": "some-rel",
                      "rt": "oic.r.temperature",
                      "if": "oic.if.a"
                    },
                    {
                      "href": "coaps://IP-ADDR/temp",
                      "rel": "some-rel",
                      "rt": "oic.r.temperature",
                      "if": "oic.if.s"
                    }
                  ],
                  "permission": 31,
                  "validity": [
                    [ "20160101T180000Z/20170102T070000Z", [ "DSTART:XXXXX", "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ] ],
                    [ "20160101T180000Z/PT5H30M", [ "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ] ]
                  ]
                }
              ],
              "aces2": [
                {
                  "subject": {
                    "rl": {
                      "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                      "roles": [
                        "SOME_STRING", "SOME_STRING"
                      ]
                    }
                  },
                  "resources": [
                    {
                      "href": "coaps://IP-ADDR/light",
                      "rel": "some-rel",
                      "rt": "oic.r.light",
                      "if": "oic.if.a"
                    },
                    {
                      "href": "coaps://IP-ADDR/door",
                      "rel": "some-rel",
                      "rt": "oic.r.door",
                      "if": "oic.if.a"
                    }
                  ],
                  "permission": 15
                }
              ]

            },
            "signature": {
              "sigtype": "oic.sec.sigtype.pk7",
              "sigvalue": "ENCODED-SIGNATURE-VALUE"
            },
            "amsid": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
            "ams": {
              "sl": [ "oic.sec.svc.doxs", "oic.sec.svc.bss" ]
            }
          }

    responses:
      201:
        description: The ACL entry is created.
      204:
        description: The ACL entry is updated.
      400:
        description: The request is invalid.

  put:
    description: |
      Sets the sacl resource data
    body:
      application/json:
        schema: Sacl
        example: |
          {
            "aclist": {
              "aces": [
                {
                  "subjectid": "e61c3e6b-9c54-4b81-8ce5-f9039c1d04d9",
                  "resources": [
                    {
                      "href": "coaps://IP-ADDR/temp",
                      "rel": "some-rel",
                      "rt": "oic.r.temperature",
                      "if": "oic.if.a"
                    },
                    {
                      "href": "coaps://IP-ADDR/temp",
                      "rel": "some-rel",
                      "rt": "oic.r.temperature",
                      "if": "oic.if.s"
                    }
                  ],
                  "permission": 31,
                  "validity": [
                    [ "20160101T180000Z/20170102T070000Z", [ "DSTART:XXXXX", "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ] ],
                    [ "20160101T180000Z/PT5H30M", [ "RRULE:FREQ=DAILY;UNTIL=20180131T140000Z;BYMONTH=1" ] ]
                  ]
                }
              ],
              "aces2": [
                {
                  "subject": {
                    "rl": {
                      "authority": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
                      "roles": [
                        "SOME_STRING", "SOME_STRING"
                      ]
                    }
                  },
                  "resources": [
                    {
                      "href": "coaps://IP-ADDR/light",
                      "rel": "some-rel",
                      "rt": "oic.r.light",
                      "if": "oic.if.a"
                    },
                    {
                      "href": "coaps://IP-ADDR/door",
                      "rel": "some-rel",
                      "rt": "oic.r.door",
                      "if": "oic.if.a"
                    }
                  ],
                  "permission": 15
                }
              ]

            },
            "signature": {
              "sigtype": "oic.sec.sigtype.pk7",
              "sigvalue": "ENCODED-SIGNATURE-VALUE"
            },
            "amsid": "484b8a51-cb23-46c0-a5f1-b4aebef50ebe",
            "ams": {
              "sl": [ "oic.sec.svc.doxs", "oic.sec.svc.bss" ]
            }
          }

    responses:
      201:
        description: The signed ACL entry is created.
      400:
        description: The request is invalid.

  delete:
    description: |
      Deletes the signed ACL data.
      When DELETE is used without query parameters, the entire collection is deleted.
      When DELETE is used with the query parameter where "acl" is specified, only the matched entry is deleted.
    queryParameters:
        subject:
            type: string
            description: |
              Delete the signed ACL identified by the string containing subject UUID.
            required: false
            example: |
              DELETE /mysacl?acl="de305d54-75b4-431b-adb2-eb6b9e546014, ..."
    responses:
      200:
        description: The signed ACL instance or the the entire signed ACL resource has been successfully deleted.
      400:
        description: The request is invalid.
